/*
 * nn_risk_model_int8.h
 * INT8 Quantized Neural Network Risk Assessment Model
 * Auto-generated by train_nn_risk_model.py
 *
 * Architecture: 6 -> 24 -> 16 -> 3 (619 parameters,
 * 619 bytes of INT8 weight/bias storage). The layer sizes come from
 * nn_risk_model.h so this header and the float32 model can never drift apart.
 */

#ifndef NN_RISK_MODEL_INT8_H
#define NN_RISK_MODEL_INT8_H

#include <stdint.h>
#include "nn_risk_model.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Quantized Model Structure */
typedef struct {
    int8_t  W1[NN_HIDDEN1_SIZE][NN_INPUT_SIZE];
    int8_t  b1[NN_HIDDEN1_SIZE];
    int8_t  W2[NN_HIDDEN2_SIZE][NN_HIDDEN1_SIZE];
    int8_t  b2[NN_HIDDEN2_SIZE];
    int8_t  W3[NN_OUTPUT_SIZE][NN_HIDDEN2_SIZE];
    int8_t  b3[NN_OUTPUT_SIZE];
} nn_model_int8_t;

/* Quantization Parameters (per-tensor scales & zero-points) */
typedef struct {
    float W1_scale, W2_scale, W3_scale, b1_scale, b2_scale, b3_scale;
    float act1_scale, act2_scale, act3_scale;
    int8_t W1_zp, W2_zp, W3_zp, b1_zp, b2_zp, b3_zp;
    uint8_t act1_zp, act2_zp, act3_zp;
} nn_quant_params_t;

/* Extern declarations */
extern const nn_model_int8_t nn_default_model_int8;
extern const nn_quant_params_t nn_quant_params;

/* INT8 Inference API */
void nn_predict_int8(
    const nn_model_int8_t *model,
    const nn_quant_params_t *qparams,
    float hr, float rmssd, float spo2,
    float temp, float hum, float pm25,
    nn_output_t *out
);

#ifdef __cplusplus
}
#endif

#endif /* NN_RISK_MODEL_INT8_H */
