/*
 * nn_risk_model.c — TinyML Neural Network Inference Engine
 * SIH26181: AI-Powered Personal Health Companion (Qualcomm)
 *
 * Implements a 2-layer feedforward neural network for real-time
 * multi-disaster health risk prediction on edge devices.
 *
 * Architecture:  Input(6) → Dense(12, ReLU) → Dense(3, Sigmoid)
 * Total params:  6×12 + 12 + 12×3 + 3 = 123 weights = 492 bytes
 * Inference:     108 MACs per prediction (< 1 µs on ARM Cortex-A9)
 *
 * Training methodology:
 *   Weights were fit by real gradient descent (Adam, 400 epochs, MSE loss)
 *   against 50,000 synthetic samples labeled by the rule-based CTSI/PRSI/
 *   flood scoring system (disaster_risk_engine.c) as the distillation
 *   teacher. See train_nn_risk_model.py for the full training script.
 *   On a 2,000-sample held-out set (never seen during training), the
 *   trained network correlates with the teacher at r=0.97 (heat),
 *   r=0.97 (pollution), r=0.94 (flood), with 78-89% exact risk-band
 *   agreement (NORMAL/MODERATE/HIGH/CRITICAL). Flood is the weakest of
 *   the three because this 6-feature input has no dedicated skin-
 *   temperature channel, so it approximates cold-exposure risk from
 *   ambient temperature alone.
 *
 *   In production deployment on Qualcomm AI Engine, the model would be
 *   retrained on clinical datasets (e.g., PhysioNet MIMIC-IV wearable
 *   vitals) and compiled to a .dlc container via SNPE/QNN SDK.
 *
 * Activation functions:
 *   Hidden: ReLU    — max(0, x)      — efficient on DSP (single compare)
 *   Output: Sigmoid — 1/(1+exp(-x))  — maps to [0,1] probability
 */

#include "nn_risk_model.h"
#include <math.h>

/* ================================================================
 *  Activation Functions
 * ================================================================ */

static float relu(float x) {
    return (x > 0.0f) ? x : 0.0f;
}

static float sigmoid(float x) {
    /* Clamp input to prevent exp() overflow on embedded platforms */
    if (x > 10.0f)  return 1.0f;
    if (x < -10.0f) return 0.0f;
    return 1.0f / (1.0f + expf(-x));
}

/* ================================================================
 *  Feature Normalization
 * ================================================================
 *  Min-max scaling: x_norm = (x - min) / (max - min) → [0, 1]
 *  This ensures all features contribute equally regardless of their
 *  physical units (BPM vs °C vs µg/m³).
 */
static float normalize(float val, float min_val, float max_val) {
    float norm = (val - min_val) / (max_val - min_val);
    /* Clamp to [0, 1] for out-of-range inputs */
    if (norm < 0.0f) norm = 0.0f;
    if (norm > 1.0f) norm = 1.0f;
    return norm;
}

/* ================================================================
 *  Pre-Trained Model Weights
 * ================================================================
 *
 *  Weight design rationale (knowledge distillation from CTSI/PRSI):
 *
 *  Hidden neurons are specialized feature detectors:
 *    H0-H3:  Heat risk detectors (respond to high temp, high HR, low RMSSD)
 *    H4-H7:  Pollution risk detectors (respond to high PM2.5, low SpO2)
 *    H8-H11: Flood/cold risk detectors (respond to low temp, extreme HR)
 *
 *  Output neurons aggregate their respective detector groups.
 *
 *  Verified outputs on this project's own canonical demo scenarios
 *  (see main_simulation.c and compare_harness.c):
 *    - Normal Resting (25°C, HR=72, SpO2=98%)         → heat=0.07  pollution=0.12  flood=0.06
 *    - Heat Wave (Delhi 47°C, HR=140, RMSSD=8)        → heat=0.83  (rule engine: CRITICAL)
 *    - Severe Smog (PM2.5=400, SpO2=86%)              → pollution=0.92  (rule engine: CRITICAL)
 *    - Flash Flood/Hypothermia (6°C, RMSSD=6)         → flood=0.54  (rule engine: CRITICAL)
 */

/* Auto-generated by train_nn_risk_model.py — real gradient-descent fit,
 * distilled from the CTSI/PRSI/flood rule engine in disaster_risk_engine.c.
 * Paste this in place of the `default_model` initializer body in nn_risk_model.c
 * Final train_mse=0.00370
 */
static const nn_model_t default_model = {
    .W1 = {
        { -0.209833f,  0.072789f, -0.020244f,  2.547783f,  0.077890f, -0.006233f },
        { -0.093441f,  0.019074f, -0.204326f,  0.194599f, -0.005375f,  1.209286f },
        {  0.136419f, -0.028576f, -0.097752f, -0.029071f, -0.022326f, -1.655743f },
        { -0.130202f, -2.240849f, -0.022094f,  0.169095f, -0.026191f,  0.011137f },
        { -2.695268f,  0.049833f,  0.009109f, -0.680536f, -0.006513f, -0.005892f },
        {  2.561465f,  0.013708f,  0.008444f, -0.560077f, -0.014107f,  0.001502f },
        { -0.133336f, -1.795159f, -0.009608f, -0.125028f,  0.002989f, -0.002440f },
        { -2.478677f,  0.036038f, -0.013320f,  0.209338f, -0.005801f,  0.013733f },
        { -0.361249f, -0.397144f,  0.060808f,  0.340282f,  0.070072f, -0.053094f },
        {  0.179512f, -0.015233f, -0.005108f,  1.432641f,  0.031005f,  0.031384f },
        {  2.058246f,  0.025932f,  0.007225f,  0.405939f, -0.005403f, -0.118477f },
        {  0.117599f, -0.010628f,  2.212906f, -0.009460f,  0.014320f,  0.144627f },
    },
    .b1 = { -1.343528f,  0.174328f,  0.570941f,  0.481745f,  1.454804f, -0.331796f,  0.902218f,  1.565012f,  0.228646f, -0.236927f,  0.029432f, -1.345512f },
    .W2 = {
        {  1.718732f, -0.105301f,  0.006202f,  0.580319f, -0.246806f,  0.858964f,  1.602564f, -1.349903f,  0.537189f,  0.473972f, -0.952487f,  0.007979f },
        { -0.007954f,  1.139447f, -1.556182f,  0.532575f,  0.116499f,  0.474987f,  0.556647f, -0.802373f, -0.027134f,  0.231917f, -0.446390f, -2.112116f },
        {  1.792566f, -0.105240f,  0.013179f,  1.984097f,  2.663684f,  2.323762f,  0.214463f, -1.799940f, -0.039697f, -1.256814f, -1.728963f,  0.034719f },
    },
    .b2 = { -0.650193f,  1.135125f, -0.329304f },
};

/* ================================================================
 *  Public API
 * ================================================================ */

const nn_model_t* nn_get_default_model(void) {
    return &default_model;
}

void nn_predict(
    const nn_model_t *model,
    float hr, float rmssd, float spo2,
    float temp, float hum, float pm25,
    nn_output_t *out
) {
    int i, j;
    float input[NN_INPUT_SIZE];
    float hidden[NN_HIDDEN_SIZE];
    float output[NN_OUTPUT_SIZE];

    /* ---- Step 1: Feature Normalization (min-max scaling to [0,1]) ---- */
    input[0] = normalize(hr,    NN_HR_MIN,    NN_HR_MAX);
    input[1] = normalize(rmssd, NN_RMSSD_MIN, NN_RMSSD_MAX);
    input[2] = normalize(spo2,  NN_SPO2_MIN,  NN_SPO2_MAX);
    input[3] = normalize(temp,  NN_TEMP_MIN,  NN_TEMP_MAX);
    input[4] = normalize(hum,   NN_HUM_MIN,   NN_HUM_MAX);
    input[5] = normalize(pm25,  NN_PM25_MIN,  NN_PM25_MAX);

    /* ---- Step 2: Hidden Layer — z = W1 * x + b1, a = ReLU(z) ---- */
    for (i = 0; i < NN_HIDDEN_SIZE; i++) {
        float sum = model->b1[i];
        for (j = 0; j < NN_INPUT_SIZE; j++) {
            sum += model->W1[i][j] * input[j];
        }
        hidden[i] = relu(sum);
    }

    /* ---- Step 3: Output Layer — z = W2 * h + b2, a = Sigmoid(z) ---- */
    for (i = 0; i < NN_OUTPUT_SIZE; i++) {
        float sum = model->b2[i];
        for (j = 0; j < NN_HIDDEN_SIZE; j++) {
            sum += model->W2[i][j] * hidden[j];
        }
        output[i] = sigmoid(sum);
    }

    /* ---- Step 4: Store results ---- */
    out->heat_score      = output[0];
    out->pollution_score = output[1];
    out->flood_score     = output[2];
}
