#!/usr/bin/env python3
"""Convert the ForgeFPGA MCU bitstream into a C header for the ESP32 firmware.

Why this exists
---------------
The ESP32-S3 programs the ForgeFPGA over SPI2 at every boot, so the bitstream has
to be linked into the firmware image. This script turns
`forgefpga_project/ffpga/build/bitstream/FPGA_bitstream_MCU.bin` into
`firmware/shrikefi/forgefpga_bitstream.h`.

Two properties matter, and both were broken at least once:

1. The array must be ``static const``. It is defined in a header; without
   ``static`` any second translation unit that includes it gets a duplicate
   symbol at link time. The generator used to emit plain ``const`` and the
   checked-in header had been hand-fixed to ``static const`` -- so simply
   regenerating silently reintroduced the bug. Do not remove the ``static``.

2. The header must correspond to the *current* bitstream. A stale header means
   the firmware flashes an old netlist and every RTL measurement taken against
   the source tree is meaningless. The source SHA-256 is recorded in the header
   and ``--check`` verifies it, so drift is detectable instead of silent.

Usage
-----
    python convert_bitstream.py            # regenerate the header
    python convert_bitstream.py --check    # exit 1 if the header is stale

Exit codes: 0 ok, 1 stale or invalid input.
"""

import argparse
import hashlib
import os
import sys

DEFAULT_BIN = os.path.join("forgefpga_project", "ffpga", "build", "bitstream",
                           "FPGA_bitstream_MCU.bin")
DEFAULT_OUT = os.path.join("..", "..", "firmware", "shrikefi",
                           "forgefpga_bitstream.h")

ARRAY_NAME = "forgefpga_bitstream"


def render_header(binary_data, sha256_hex):
    """Build the exact header text for a given bitstream."""
    lines = []
    lines.append("// Auto-generated by convert_bitstream.py -- DO NOT EDIT")
    lines.append("// Source: %s" % os.path.basename(DEFAULT_BIN))
    lines.append("// Size: %d bytes" % len(binary_data))
    lines.append("// Source-SHA256: %s" % sha256_hex)
    lines.append("")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")

    # static is load-bearing: this header has no separate .c file, so without it
    # every including translation unit defines a second copy of the symbol.
    lines.append("static const uint32_t %s_length = %d;"
                 % (ARRAY_NAME, len(binary_data)))
    lines.append("static const uint8_t %s[] = {" % ARRAY_NAME)

    # Byte formatting deliberately mirrors the original generator (", " between
    # bytes, a newline every 12) so regenerating after a re-fit produces a diff
    # containing only the bytes that actually changed.
    parts = []
    for i, b in enumerate(binary_data):
        parts.append("0x%02X" % b)
        if i < len(binary_data) - 1:
            parts.append(", ")
        if (i + 1) % 12 == 0:
            parts.append("\n    ")
    lines.append("    " + "".join(parts).rstrip())

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def convert_bin_to_header(bin_path, header_path):
    if not os.path.exists(bin_path):
        print("Error: Bitstream file not found at %s" % bin_path)
        return False
    try:
        with open(bin_path, "rb") as f:
            binary_data = f.read()
        sha256_hex = hashlib.sha256(binary_data).hexdigest()
        text = render_header(binary_data, sha256_hex)
        with open(header_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("Success: Wrote %d bytes to %s" % (len(binary_data), header_path))
        print("         Source-SHA256: %s" % sha256_hex)
        return True
    except Exception as e:
        print("Error during conversion: %s" % e)
        return False


def check_header(bin_path, header_path):
    """Exit non-zero if the header does not match the bitstream on disk."""
    if not os.path.exists(bin_path):
        print("error: bitstream not found: %s" % bin_path)
        return False
    if not os.path.exists(header_path):
        print("error: header not found: %s" % header_path)
        return False

    with open(bin_path, "rb") as f:
        binary_data = f.read()
    sha256_hex = hashlib.sha256(binary_data).hexdigest()
    expected = render_header(binary_data, sha256_hex)
    with open(header_path, "r", encoding="utf-8") as f:
        actual = f.read()

    if actual != expected:
        print("error: stale generated header: %s" % header_path)
        print("       re-run hardware/shrikefi/convert_bitstream.py")
        return False

    print("ok: %s matches %s (%d bytes, sha256 %s)"
          % (header_path, os.path.basename(bin_path), len(binary_data),
             sha256_hex[:16] + "..."))
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the generated header is stale")
    parser.add_argument("bin", nargs="?", default=DEFAULT_BIN,
                        help="input bitstream .bin")
    parser.add_argument("out", nargs="?", default=DEFAULT_OUT,
                        help="output C header")
    args = parser.parse_args()

    # Resolve relative to this script so it works from any working directory.
    script_dir = os.path.dirname(os.path.abspath(__file__))
    bin_abs = os.path.normpath(os.path.join(script_dir, args.bin))
    out_abs = os.path.normpath(os.path.join(script_dir, args.out))

    if args.check:
        sys.exit(0 if check_header(bin_abs, out_abs) else 1)
    sys.exit(0 if convert_bin_to_header(bin_abs, out_abs) else 1)


if __name__ == "__main__":
    main()
