import os
import sys

def convert_bin_to_header(bin_path, header_path, array_name="forgefpga_bitstream"):
    if not os.path.exists(bin_path):
        print(f"Error: Bitstream file not found at {bin_path}")
        return False
        
    try:
        with open(bin_path, 'rb') as f:
            binary_data = f.read()
            
        with open(header_path, 'w') as f:
            f.write(f"// Auto-generated by convert_bitstream.py\n")
            f.write(f"// Source: {os.path.basename(bin_path)}\n")
            f.write(f"// Size: {len(binary_data)} bytes\n\n")
            
            f.write("#pragma once\n")
            f.write("#include <stdint.h>\n\n")
            f.write(f"const uint32_t {array_name}_length = {len(binary_data)};\n")
            f.write(f"const uint8_t {array_name}[] = {{\n    ")
            
            for i, byte in enumerate(binary_data):
                f.write(f"0x{byte:02X}")
                if i < len(binary_data) - 1:
                    f.write(", ")
                if (i + 1) % 12 == 0:
                    f.write("\n    ")
                    
            f.write("\n};\n")
            
        print(f"Success: Wrote {len(binary_data)} bytes to {header_path}")
        return True
        
    except Exception as e:
        print(f"Error during conversion: {e}")
        return False

if __name__ == "__main__":
    # Default paths based on the ForgeFPGA project output
    bin_file = r"..\..\FPGA-MED-DEVICE\ffpga\build\bitstream\FPGA_bitstream_MCU.bin"
    out_file = r"..\..\firmware\shrikefi\forgefpga_bitstream.h"
    
    if len(sys.argv) == 3:
        bin_file = sys.argv[1]
        out_file = sys.argv[2]
        
    # Ensure absolute paths based on script location
    script_dir = os.path.dirname(os.path.abspath(__file__))
    bin_file_abs = os.path.normpath(os.path.join(script_dir, bin_file))
    out_file_abs = os.path.normpath(os.path.join(script_dir, out_file))
    
    convert_bin_to_header(bin_file_abs, out_file_abs)
