- name: TruffleHog Secret Scanner
  uses: trufflesecurity/trufflehog@main
  with:
    path: ./
    base: ${{ github.event_name == 'push' && github.event.before || github.event.repository.default_branch }}
    head: ${{ github.event_name == 'push' && github.event.after || 'HEAD' }}
    extra_args: --debug --only-verified
